### ISSUE TITLE
UnLazy - not working on wikihow

### ISSUE THREAD

**Issue by NijazM** [eladkarako/chrome_extensions#1]
I noticed that it does not really work on wikihow in firefo, although it says on icon that 22 requests have been modified, and I see in network monitor that really 1st image request is double, 1st one is original one, and another one is new one, but only for step 1 image, not others. When I scroll down I have to wait for lazy loading to do its work.

Example url: https://www.wikihow.com/Activate-the-Touchpad-on-a-Laptop

**Comment by NijazM** [comment]
I said Firefox, not Chrome. In Chrome it works OK. I tried last version.

**Comment by eladkarako** [comment]
sorry...

**Comment by eladkarako** [comment]
> Also I noticed that it prevents some websites from displaying images at all.

let me know and I'll fix it.

<hr/>

It seems to be working well,  
there is a little class on the image (that would surely be removed by the website's lazyloading engine once it is complete), that hides the image (but keeps its place - using CSS- visibility).  

The UnLazy is already prepared for that and it counters all those "hiding" $h!t...

![2020-08-24_231943](https://user-images.githubusercontent.com/415238/91092264-6a20ba00-e660-11ea-8809-d020b0225ea8.png)

<hr/>

try to see if you are happen to interact with Firefox's **new** native lazyloading.
set <code>dom.image-lazy-loading.enabled</code> to <code>false</code>.

I was testing using and old ESR firefox (the developer panel in new FF is $h!t).  
but I now upgrading to latest nightly to check if it is related.

if it does,  
all I have to do is add few attributes to the "fixed" image, 
to avoid it being "re"lazyify by the browser's own native lazyloading 
(<code>loading="eager"</code> and <code>lazyload="off").  

you know what... I'll add it right now anyway!

**Comment by eladkarako** [comment]
Oh I've got it!

some images keeps showing "loading" shows.
I take back what I've said about the websites.
there is a problem with its custom-made lazyloading, 
the images that you sometimes see "keep loading" (loading animation), 
right click those, 
you'll see an <code>img</code> without src, srcset,data-src, etc...

the websites is glitching, hard refresh (ctrl+f5),  
and you'll see the the image loading fine.  

it might be a glitch, it might be something else, 
it is not related to the unlazy web-extension, since the first thing the unlazy webextension does is write "unlazy" attribute over the image, 

I suspect that the websites-custom made removes the data-src for some reason, but does not write it (back in the 90's websites used to load the image in the background "for cache" - stupid is f**k, but maybe the cause),  

anyway I'll update the unlazy with some stuff the might help you,  
but otherwise it is out of the web-extension scope.

b.t.w.  

here are cool stuff you can try to make images show faster (regardless of lazy/unlazy stuff).

pref("image.decode-immediately.enabled", true);
pref("image.downscale-during-decode.enabled", false);
pref("image.high_quality_downscaling.enabled", false);
pref("image.multithreaded_decoding.enabled", true);
pref("image.multithreaded_decoding.limit", 2);
pref("image.single-color-optimization.enabled", false);

took it from my custom firefox profile.

https://github.com/eladkarako/mods/blob/store/Firefox/_mozilla.cfg_

**Comment by NijazM** [comment]
Wow, when I set dom.image-lazy-loading.enabled to false it works OK now.
Also possible reason why you might have not noticed it is because you use too fast internet.
My speed is that of 2G, around 20 kB/s. The website was acting same as without your extension until I change this in about config.

As for loading animation on related articles, it is still present. Right clicking reveals that it has src code jut fine.
Hard refresh does not fix it. Also such animation gets saved by 'save page we' and persists even if opened with chrome.

Here is code of same related image which appears in related articles to the right and to the bottom. Right ones have waiting animation, while bottom don't. I thought changing class of bottom one to the top one will fix problem but still nothing, only gets glitched even more, while if I remove class, image is still same.

```<img id="a4e0e2f6e91a0bae56f4dc3d17c20ade" alt="" class="img-loading-hide" unlazy="" style="" src="https://www.wikihow.com/images/thumb/8/8e/Take-a-Photo-by-Camera-on-a-Laptop-Step-13.jpg/-crop-127-140-127px-Take-a-Photo-by-Camera-on-a-Laptop-Step-13.jpg" width="127" height="140">

<img id="bf8ac6880f8947ebd11e0e4b37f539c4" class="scrolldefer content-fill img-loading-hide" alt="" unlazy="" style="" src="https://www.wikihow.com/images/thumb/8/8e/Take-a-Photo-by-Camera-on-a-Laptop-Step-13.jpg/-crop-342-184-245px-Take-a-Photo-by-Camera-on-a-Laptop-Step-13.jpg" width="342" height="184">```

**Comment by eladkarako** [comment]
try updating to the new unlazy I've uploaded. 
thanks to you opening this issue here, I've improved it a lot. 
I've added certain attributes to the clean new image, that makes sure that even if the user has "browser native lazyloading ON" it will not effect the image (the browser native lazyloading will ignore that image), 
second thing I've put is to render images in parallel. 

thank you for your help!

<hr/>

If you want some more speed, especially if your broadband is limited try installing boostaler, ublock origin (it blocks additional connection of garbage) and setting your DNS servers (preferably in your router, for your home wifi) to AdBlock DNS: <code>176.103.130.130</code> <code>176.103.130.131</code>, it will block most of the ads and banners (which when you think about it are kind of big images, which is a lot of traffic...)

**Comment by eladkarako** [comment]
> Also you say it is not related to your extension, but I think it is, because without extension it does not appear.

of course, 
unlazy breaks many kinds lazyloading of the page, by directly loading the image,  
if the page "expected" the image to be loading and triger an image onload/onerror event,  
in which the page would "do stuff" such as removing a "loading animation":  
it is a problem. not a bug. a problem.

UnLazy can not, and would not (sorry!) take care of hiding the design of the elements that are "too" far away from the image it tries to fix. You can probably take care of it by removing the animation container or blocking the image file using something like a ublock-origin, so it will never bother you.  
in your case, 
I would strongly recommend you disable the javascript support for the page,  
in whatever browser you're using.  
This specific page will work well without javascript, for presentation.
