### ISSUE TITLE
AMO shenanigans

### ISSUE THREAD

**Issue by atomGit** [eladkarako/chrome_extensions#15]
why do you keep publishing/removing/republishing your add-ons on AMO?

**Comment by eladkarako** [comment]
Sorry about that, 
Mozilla reviewers keeps either marking my web-extensions 'incomplete' ("you need to upload a newer version") or 'disabled' ("you have to upload a brand new web-extension with new generated signature since we've blocked your current web-extension from being installed on our Firefox browsers").

Just the at the start of the week a reviewer marked 4 web-extension disabled, 
putting them in this Mozilla-bugzilla-bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1602022 (feel free to view/look for items with "@eladkarako.com"), 

after hours of me trying to figure out how/why, 
I've got a very rude reply, which I won't going to repeat in here..., 
saying my web-extensions are 'obfuscated' for some reason, 
and since I'm also hosting them on 3'rd party website (in this project-releases section), 
he (the reviewer) felt that he should also mark them as "blocked" so the browser will download its daily "block-listed" addons, any installed instances will be blocked as well.

I was sending both the reviewer and the generic email asap. response that none of the code I've submitted to firefox not even minified for whitespace, but didn't got reply so far (6 emails were sent by me... the last email includes a screenshot of every file in the XPI archive showing that I, in-fact have plain text content everywhere) - regardless, I was not really answered yet.

I'm not the only one having problems with the guys reviewing web-extension or the general way which are developers are addressed by, which is not the nicest way, 
so as long my web-extensions are marked as "approved", 
which means they are signed by the mozilla-server and ready for installation on Firefox (desktop/mobile) I download the signed XPI, 
and upload it, as a backup to https://github.com/eladkarako/chrome_extensions/releases/tag/LatestFirefox

where I and other users can have a 24/7 ability to download/use/reivew its content (archive) without being too depend on its ability on the AMO website, I don't have them generally available there anyway.
some time I preform a more-than usual update the includes various other web-extension (I base my web-extensions on a kind of a template I've designed which works well for me, and from time to time I update it, which means about 30+ web-extensions will get an updated version), 
in that case I upload every few hours a new web-extension, and wait for it to get approved, 
this whole thing takes about few days, 
so if you've being noticing that the web-extension suddenly available for download, 
that is the reason.

so to your question, 
the web-extensions I've designed/alpha-testing/use are to be accessed from this repository's release section, where they are available 24/7. Any shenanigans (I love that word :]) are indirectly related to some nasty annoyances introduced by the AMO reviewers or the nice people maintaining https://github.com/mozilla/addons-server 

that was quite long explanations. 
I hope I've found that informative and entertaining...

happy holidays :) 🎄🕎 🎁🎅
