### ISSUE TITLE
Speedy-Rendering breaks some of nytimes.com

### ISSUE THREAD

**Issue by yokoffing** [eladkarako/chrome_extensions#21]
URL: `https://www.nytimes.com/2020/03/26/world/coronavirus-news.html`
See: https://postimg.cc/vcVqzrYB
Firefox 74 Stable
I am using uBlock Origin and [Bypass Paywalls Clean](https://github.com/magnolia1234/bypass-paywalls-firefox-clean).

**Comment by eladkarako** [comment]
Thanks for taking the time to screenshot the bug, 
I'm not sure what the bug is, it looks like it's related to CSS-<code>*transition*</code> attributes (which some websites uses, to position a content around the page), 
but I've previously removed anything that caused issues with that already...

Assuming you're using the latest version, I need to check it..

**Comment by eladkarako** [comment]
right, 
I'm loading the page (Chrome) with JavaScript disabled and it seems fine..

**Comment by eladkarako** [comment]
It looks fine to me.

b.t.w. I block the following domains, 
(which might disable some problematic 3'rd-party JavaScript files):

<pre>
www.google-analytics.com
cdn.optimizely.com
meter-svc.nytimes.com
js.datadome.co
www.googletagmanager.com
securepubads.g.doubleclick.net
</pre>

You can try updating the web-extensio to the latest version and 
adding those the the custom-filters in uBlock-origin.
