### ISSUE TITLE
UnLazy YouTube?

### ISSUE THREAD

**Issue by exec228** [eladkarako/chrome_extensions#22]
Salut!

I have installed https://github.com/eladkarako/chrome_extensions/releases/download/LatestFirefox/unlazy-8.0.6.9-an+fx.xpi onto Firefox 77.0.1x64.

Yet, youtube still starts to load when I switch to tab.

Repro:
1) Open youtube, say, subscriptions.
2) Middle click on any video link to open a background tab
3) Wait until this background tab obtains a favicon instead of a spinner
4) Switch to this tab
5) Witness youtube wakes up and begins a paused page load, because it stopped load just on main layout
Expected:
5) See the page fully loaded with all icons, and thumbnails, and preview pictures, et al, at least to 1000px height.

What am I doing wrong?

I open most of pages in background, therefore this UnLazy addon is quite important to me.

**Comment by exec228** [comment]
Same with https://github.com/eladkarako/chrome_extensions/releases/download/LatestChrome/UnLazy_8.0.6.9.zip on Chrome 83.0.4103.116 (Official Build) (64-bit)

**Comment by eladkarako** [comment]
YouTube will load "chunks", in a continues manner as long you'll progress downwards, 
meaning if you'll scroll down, you you'll see additional content.

UnLazy works pretty well on existing content on the page,  
so you'll expect all video-thumbnails (pictures of videos) will load without delay.  

as for when YouTube adds a new part to the page with new videos,  
I'll try to make the algorithm (which is generic, and NOT YouTube specific),  
to re-discover those too.  

I <em>currently</em> "listen" (at-least try to "listen") to YouTube "events", from the page ("the SPF engine") and player, URL history-API refreshing from the browsers, and even page resize or transition-end (for when an animation stops),  
I have also a sort of "timer" that checks the page every 1 minute (its called an Alarm-API, and Google won't allow running it faster than that),
all this to try to discover new thumbnails to "unlazy".

Sometimes it simply does not discover them fast enough sorry.

try the newer version. but it should be the same.

I'll look into this issue, 
mybe I'll have a new idea on a new manner to discover new elements on the page, 
that does not require any "old timeouts/interval" or object-observing which is $hit for browser performances.

due to there not anything I can do right now I close this issue, 
the current algorithm is already trying "its best..."..
