### ISSUE TITLE
UnLazy: Whitelist and notification

### ISSUE THREAD

**Issue by Peuj** [eladkarako/chrome_extensions#3]
**Is your feature request related to a problem? Please describe.**
When something get wrong on a specific website my only solution is to go to "Add-ons Manager" to disable UnLazy and reload the page.
Of course I'm doing this without being sure UnLazy has `kill dynamically-loaded images engines`.
Then once I'm done with this page, I have to go to "Add-ons Manager" and enable UnLazy.

**Describe the solution you'd like**
1- I would like to know that UnLazy has `kill dynamically-loaded images engines`.
This could be done with the browser action button by changing the icon color or the badge text.
2- I would like to be able to whitelist an url in case UnLazy breaks something.

Thanks

**Comment by eladkarako** [comment]
keeping it very simple for now,
'dirtying up' the pure functional-code with UI-functionality will eventually be added (allow-list and profile-sync settings), but not for few months. currently the web-extension does a similar work to a userscript (in functionality, but using the browser extension-infrastructure it works better and more efficiently).
the icon-number ("badge") is only updated when there was any change, 
if there was none, it means the web-extension did not recognised (..pattern matching) any reason to kill a lazyloading mechanism (mostly because there was none..).
for enabling/disabling it, it's the extension-manager for now... :|
