### ISSUE TITLE
UnShorts compatibility with Twitter use of bit.ly

### ISSUE THREAD

**Issue by grahamperrin** [eladkarako/chrome_extensions#4]
Please, can you make UnShorts work with bit.ly in tweets? 

At https://twitter.com/TIPConsortium/status/1148892293673435136 for example. 

If it helps: legacy **Long URL Please Mod** [works as expected](https://new.reddit.com/r/firefox/comments/cccjv4/successors_to_the_long_url_please_mod_extension/). 

Thanks

**Comment by eladkarako** [comment]
UnShorts is relatively new web-extension, it is still quirky.

<strong>in twitter you don't actually get what you see in-front of you:</strong>
all of the links are converted to a twitter short link first, 
regardless to where they are pointing to, 

once you've gone through the twitter short URL, 
you actually get the short-URL you are clicking on (the <code>bit.ly</code> one).

For now install 'Remove-Redirects' web-extension, 
it will strip the twitter short-links <strong>without the need to make any network resolving</strong>,
and it will rewrite a clean link back pointing to the <code>bit.ly</code> code.
if you have UnShorts installed, it will then identify a "new" <code>bit.ly</code> link, 
and the UnShorts then will use network resolving through <code>http://9inchurl.com/api.php?url=...</code> and will rewrite the link to point to the real one.

eventually the job should be done in less then 3 seconds.

I might merge those two web-extensions together eventually.
for now... I need to update them both to also run every 300ms to complete one another even when one has finished (endless loop)...
update will be up in few moments.

Thanks for the bug report,
I'm not closing it yet because it is very useful to me!
it presents an idea and opportunity for improving both of those web-extensions,
thanks for that!

**Comment by grahamperrin** [comment]
Thanks! 

https://github.com/eladkarako/chrome_extensions/releases/download/LatestFirefox/remove_redirects_plus-2.1.1.115-an+fx.xpi added a rarely used, minimally extended profile: 

- initial results were good (fully qualified URL)

– however, I then realised that I had forgotten to disable UnShorts 1.0.5.13. 

After disabling UnShorts I couldn't get Remove-Redirects-Plus 2.1.1.119 (updated automatically, I guess) to work. 

I'm very grateful for your work on this but to be honest, if it's for me alone then I shouldn't ask you to put any more time on it. 99% of my browsing is with Waterfox Classic 56.2.12 (historically: Waterfox 56.0 was based on Firefox 56.0.2) so my interest in Firefox Quantum is sort of peripheral :-)

**Comment by eladkarako** [comment]
@grahamperrin I'm glad to add/improve my web-extensions, 
and thankful for your help with-it, 

thanks to your issue-ticket, I've created a new web-extension (well.. merged two other anyway...)

I've recently uploaded everything to Firefox's official add-on website,
so you can try getting it from https://addons.mozilla.org/en-GB/firefox/addon/remove-redirects-plus/
(I had problems with uploading to Mozilla servers before, but hopefully all my uploaded work will stay up this time...)

None of my web-extensions save any data on the browser, nor storage/cookie or anything, 
you should be able to install remove-redirects-plus and uninstall remove-redirects and unshorts in-any order you like to without any issues.

If it stopped working it might be another issue, 
try removing/installing the new one and feel free to let me know if it's working or not.
