### ISSUE TITLE
[Speedy Rendering] Discord spoiler missing effect

### ISSUE THREAD

**Issue by Jorge9811** [eladkarako/chrome_extensions#9]
Speedy Rendering Disabled:
![1](https://user-images.githubusercontent.com/54429803/63569110-58d53700-c54e-11e9-93c4-61249cc95d41.png)

Speedy Rendering Enabled:
![2](https://user-images.githubusercontent.com/54429803/63569109-570b7380-c54e-11e9-8ad3-d395435fed83.png)

**Comment by Jorge9811** [comment]
im also noticing youtube's video player gets laggy when i use this extension

**Comment by eladkarako** [comment]
Speedy-Rendering shouldn't effect YouTube's video-playing (other than possibly improving it), 
the video-progressbar might have jumpy movement, this is caused by the speedy-rendering web-extension injecting a CSS-rule to minimize all transition animation (<code>transition-duration:1ms;</code>), other than that the page might be rendering text around the page in a slightly quicker and dirty way (<code>text-rendering:optimizeSpeed;</code> and <code>font-feature-settings:...</code>)
I will try to debug it to see it removing any of those will matter...
but those are expected side-effects.

The spoiler uncovering is not expected effect to installing speedy-rendering, 
but without you mentioning in which web-site did you noticed this effect, 
I can assume this 'uncovering' effect is caused by the speedy-rendering web-extension disabling some of the box-shadow effects on the page (for example), 
I can add this to a list of known (minor) issues on specific websites but I have no intention to remove the 'shadow removal' rules since it saves a lot of rendering effort from the page/browser.

movement issues 
it might be caused by one of the additional CSS-rules, placed to improve scrolling 
but I'll might

**Comment by Jorge9811** [comment]
> Speedy-Rendering shouldn't effect YouTube's video-playing (other than possibly improving it)
Then the lag while playing videos when Speedy Rendering is enabled must be a bug. I hope you can fix it.

> but without you mentioning in which web-site did you noticed this effect,
I did mention it in the title of the issue though, it's Discord.

**Comment by eladkarako** [comment]
@Jorge9811 may you send me a specific URL in Discord?

**Comment by eladkarako** [comment]
After checking to see how the 'spoiler'-feature in 'Discord'-works, 
it seems that there choice of implementing a 'covering background' was to create a very large box-shadow around the centered-'spoiler'-container, which might be considered non-standard (they havn't really covered the content in the proper z-order with another block-like container (such as the 'overlay' layer often used in MODALs, or custom-alert alternatives),
The way of implementing makes the website effected by the shadow-removal rule in the Speedy-Rendering.
This is not a bug.
